AWSTemplateFormatVersion: "2010-09-09"
Description: Provision EC2 for postgres

Parameters:
  KeyName:
    Description: The EC2 Key Pair to allow SSH Access to the instance
    Type: "AWS::EC2::KeyPair::KeyName"
  MyIP:
    Description: IP address allowed to access EC2
    Type: String
  # CentOS 7.4
  Ec2ImageId:
    Type: String
    Default: ami-0dbc4b765478a0eaf
  Ec2InstanceType:
    Type: String
    Default: t3.small

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.5.0.0/16
      Tags:
        - Key: Name
          Value: vpc-cf

  IGW:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: igw-cf

  # IGWをVPCにアタッチ
  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref IGW

  PubSubA:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: ap-northeast-1a
      VpcId: !Ref VPC
      CidrBlock: 10.5.10.0/24
      Tags:
        - Key: Name
          Value: pub-sub-a-cf

  PubSubRT:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: pub-sub-rt-cf

  # PubSub-インターネット間のルーティング
  PubSubToInternet:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PubSubRT
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref IGW

  # ルートテーブルをサブネットに関連付け
  AssoPubSubART:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PubSubA
      RouteTableId: !Ref PubSubRT

  # postgres test nodes
  EC2Postgres1: 
    Type: AWS::EC2::Instance
    Properties: 
      ImageId: !Ref Ec2ImageId
      KeyName: !Ref KeyName
      InstanceType: !Ref Ec2InstanceType
      IamInstanceProfile: !Ref EC2InstanceProfile
      NetworkInterfaces: 
        - AssociatePublicIpAddress: "true"
          DeviceIndex: "0"
          SubnetId: !Ref PubSubA
          PrivateIpAddress: 10.5.10.11
          GroupSet:
            - !Ref EC2PostgresSG
      UserData: !Base64 |
        #!/bin/bash
        # hostnameとhostsの設定 
        hostnamectl set-hostname ec2-postgres-1-cf
        cat <<EOF | sudo tee -a /etc/hosts
        10.5.10.11 ec2-postgres-1-cf
        EOF

        # PostgreSQL14.0+centos7.4初期セットアップ手順
        yum update -y


        # OS設定
        timedatectl set-timezone Asia/Tokyo
        
        
        # 必要パッケージをdnfでインストール
        yum install -y wget unzip
        yum install -y perl-libs # perl-libs is needed by postgresql-contrib 不要かも
        
        
        # その他postgreとその周辺ツールのrpmをダウンロード
        ## postgre本体で必要なパッケージ
        wget --tries=5 http://54.169.224.98/centos/7/os/x86_64/Packages/libxslt-1.1.28-6.el7.x86_64.rpm
        wget --tries=5 http://54.169.224.98/centos/7/os/x86_64/Packages/libicu-50.2-4.el7_7.x86_64.rpm
        wget --tries=5 http://54.169.224.98/centos/7/os/x86_64/Packages/python3-libs-3.6.8-17.el7.x86_64.rpm
        wget --tries=5 http://54.169.224.98/centos/7/os/x86_64/Packages/python3-3.6.8-17.el7.x86_64.rpm
        wget --tries=5 http://54.169.224.98/centos/7/os/x86_64/Packages/python3-setuptools-39.2.0-10.el7.noarch.rpm
        wget --tries=5 http://54.169.224.98/centos/7/os/x86_64/Packages/python3-pip-9.0.3-8.el7.noarch.rpm
        ## postgre本体
        wget --tries=5 --no-check-certificate https://download.postgresql.org/pub/repos/yum/14/redhat/rhel-7.4-x86_64/postgresql14-14.0-1PGDG.rhel7.x86_64.rpm
        wget --tries=5 --no-check-certificate https://download.postgresql.org/pub/repos/yum/14/redhat/rhel-7.4-x86_64/postgresql14-server-14.0-1PGDG.rhel7.x86_64.rpm
        wget --tries=5 --no-check-certificate https://download.postgresql.org/pub/repos/yum/14/redhat/rhel-7.4-x86_64/postgresql14-docs-14.0-1PGDG.rhel7.x86_64.rpm
        wget --tries=5 --no-check-certificate https://download.postgresql.org/pub/repos/yum/14/redhat/rhel-7.4-x86_64/postgresql14-libs-14.0-1PGDG.rhel7.x86_64.rpm
        wget --tries=5 --no-check-certificate https://download.postgresql.org/pub/repos/yum/14/redhat/rhel-7.4-x86_64/postgresql14-contrib-14.0-1PGDG.rhel7.x86_64.rpm
        ## postgre周辺ツール
        wget --tries=5 https://github.com/ossc-db/pg_statsinfo/releases/download/14.0/pg_statsinfo-14.0-1.rhel7.x86_64.rpm
        wget --tries=5 https://github.com/ossc-db/pg_store_plans/releases/download/1.6.1/pg_store_plans14-1.6.1-1.el7.x86_64.rpm
        wget --tries=5 --no-check-certificate https://download.postgresql.org/pub/repos/yum/14/redhat/rhel-7.4-x86_64/pg_repack_14-1.4.7-1.rhel7.x86_64.rpm
        wget --tries=5 --no-check-certificate https://download.postgresql.org/pub/repos/yum/14/redhat/rhel-7.4-x86_64/orafce_14-3.18.1-1.rhel7.x86_64.rpm
        ## postgre周辺ツール（pg_stats_reporter関連）
        wget --tries=5 https://github.com/ossc-db/pg_stats_reporter/releases/download/14.0/pg_stats_reporter-14.0-1.el7.noarch.rpm
        wget --tries=5 http://54.169.224.98/centos/7/os/x86_64/Packages/httpd-tools-2.4.6-95.el7.centos.x86_64.rpm
        wget --tries=5 http://54.169.224.98/centos/7/os/x86_64/Packages/httpd-2.4.6-95.el7.centos.x86_64.rpm
        wget --tries=5 http://54.169.224.98/centos/7/os/x86_64/Packages/php-5.4.16-48.el7.x86_64.rpm
        wget --tries=5 http://54.169.224.98/centos/7/os/x86_64/Packages/php-common-5.4.16-48.el7.x86_64.rpm
        wget --tries=5 http://54.169.224.98/centos/7/os/x86_64/Packages/php-fpm-5.4.16-48.el7.x86_64.rpm
        wget --tries=5 http://54.169.224.98/centos/7/os/x86_64/Packages/php-intl-5.4.16-48.el7.x86_64.rpm
        wget --tries=5 http://54.169.224.98/centos/7/os/x86_64/Packages/php-cli-5.4.16-48.el7.x86_64.rpm
        wget --tries=5 http://54.169.224.98/centos/7/os/x86_64/Packages/php-xml-5.4.16-48.el7.x86_64.rpm
        wget --tries=5 http://54.169.224.98/centos/7/os/x86_64/Packages/php-pdo-5.4.16-48.el7.x86_64.rpm
        wget --tries=5 http://54.169.224.98/centos/7/os/x86_64/Packages/php-pgsql-5.4.16-48.el7.x86_64.rpm
        wget --tries=5 http://54.169.224.98/centos/7/os/x86_64/Packages/apr-1.4.8-7.el7.x86_64.rpm
        wget --tries=5 http://54.169.224.98/centos/7/os/x86_64/Packages/apr-util-openssl-1.5.2-6.el7.x86_64.rpm
        wget --tries=5 http://54.169.224.98/centos/7/os/x86_64/Packages/apr-util-1.5.2-6.el7.x86_64.rpm
        wget --tries=5 http://54.169.224.98/centos/7/os/x86_64/Packages/mailcap-2.1.41-2.el7.noarch.rpm
        wget --tries=5 http://54.169.224.98/centos/7/os/x86_64/Packages/centos-logos-70.0.6-3.el7.centos.noarch.rpm
        wget --tries=5 http://54.169.224.98/centos/7/os/x86_64/Packages/libzip-0.10.1-8.el7.x86_64.rpm
        wget --tries=5 http://54.169.224.98/centos/7/os/x86_64/Packages/libgcrypt-devel-1.5.3-14.el7.x86_64.rpm
        wget --tries=5 http://54.169.224.98/centos/7/os/x86_64/Packages/libgpg-error-devel-1.12-3.el7.x86_64.rpm
        
        
        
        
        # postgreと周辺ツールのインストール
        ## postgre本体で必要なパッケージ
        ## postgre本体
        rpm -ivh libxslt-1.1.28-6.el7.x86_64.rpm \
        libicu-50.2-4.el7_7.x86_64.rpm \
        python3-libs-3.6.8-17.el7.x86_64.rpm \
        python3-3.6.8-17.el7.x86_64.rpm \
        python3-setuptools-39.2.0-10.el7.noarch.rpm \
        python3-pip-9.0.3-8.el7.noarch.rpm \
        postgresql14-14.0-1PGDG.rhel7.x86_64.rpm \
        postgresql14-server-14.0-1PGDG.rhel7.x86_64.rpm \
        postgresql14-docs-14.0-1PGDG.rhel7.x86_64.rpm \
        postgresql14-libs-14.0-1PGDG.rhel7.x86_64.rpm \
        postgresql14-contrib-14.0-1PGDG.rhel7.x86_64.rpm
        
        
        ## postgre周辺ツール
        rpm -ivh pg_statsinfo-14.0-1.rhel7.x86_64.rpm \
        pg_store_plans14-1.6.1-1.el7.x86_64.rpm \
        pg_repack_14-1.4.7-1.rhel7.x86_64.rpm \
        orafce_14-3.18.1-1.rhel7.x86_64.rpm
        ## postgre周辺ツール（pg_stats_reporter関連）
        rpm -ivh pg_stats_reporter-14.0-1.el7.noarch.rpm \
        httpd-tools-2.4.6-95.el7.centos.x86_64.rpm \
        httpd-2.4.6-95.el7.centos.x86_64.rpm \
        php-5.4.16-48.el7.x86_64.rpm \
        php-common-5.4.16-48.el7.x86_64.rpm \
        php-fpm-5.4.16-48.el7.x86_64.rpm \
        php-intl-5.4.16-48.el7.x86_64.rpm \
        php-cli-5.4.16-48.el7.x86_64.rpm \
        php-xml-5.4.16-48.el7.x86_64.rpm \
        php-pdo-5.4.16-48.el7.x86_64.rpm \
        php-pgsql-5.4.16-48.el7.x86_64.rpm \
        apr-1.4.8-7.el7.x86_64.rpm \
        apr-util-openssl-1.5.2-6.el7.x86_64.rpm \
        apr-util-1.5.2-6.el7.x86_64.rpm \
        mailcap-2.1.41-2.el7.noarch.rpm \
        centos-logos-70.0.6-3.el7.centos.noarch.rpm \
        libzip-0.10.1-8.el7.x86_64.rpm \
        libgcrypt-devel-1.5.3-14.el7.x86_64.rpm \
        libgpg-error-devel-1.12-3.el7.x86_64.rpm
        
        
        # hostname設定、SELINUX設定反映のため再起動 
        shutdown -r now

        Tags:
          - Key: Name
            Value: ec2-postgres-1-cf

  # postgres test node用SG
  EC2PostgresSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: ec2-postgres-sg-cf
      GroupDescription: Allow SSH and psql and tool
      VpcId: !Ref VPC
      SecurityGroupIngress:
        # http
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: !Ref MyIP
        # ssh
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref MyIP
        # psql
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          Description: psql
          CidrIp: 10.5.0.0/16

  EC2IAMRole: 
    Type: AWS::IAM::Role
    Properties: 
      RoleName: ec2-role-cf
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - Effect: Allow
            Principal: 
              Service: 
                - "ec2.amazonaws.com"
            Action: 
              - "sts:AssumeRole"
      Path: "/"
      ManagedPolicyArns: 
        # 検証用なのでAdmin権限付与
        - "arn:aws:iam::aws:policy/AdministratorAccess"

  EC2InstanceProfile: 
    Type: AWS::IAM::InstanceProfile
    Properties: 
      Path: "/"
      Roles: 
        - Ref: EC2IAMRole
      InstanceProfileName: ec2-instance-profile-cf


Outputs:
  EC2PublicIP1:
    Value: !GetAtt EC2Postgres1.PublicIp
    Description: Public IP of EC2 instance

